### ISSUE TITLE
레알프로젝트 시작

### ISSUE THREAD

**Issue by zeliard** [mooneegee/CloneCraft#1]
키워드 위주로 이 프로젝트를 이야기해본다면: 
C++
3D
OpenGL
Simple MineCraft
이 틀안에서 자유롭게 하면 될 것 같고

매주 한번씩 찾아오삼. 그리고, 그 주에 했던 작업 내용을 업데이트 노트 형식으로 이슈로 남겨주면 더 좋음!

이제 2달 반 가량 남았으니(5월 30일까지), 열심히 달려봅시다~~ 화이링~

**Comment by mooneegee** [comment]
위키에 업데이트 노트 작성하였습니다.
열심히 하겠습니다.
좋은 배움의 기회주셔서 감사합니다.
