### ISSUE TITLE
몇 가지 코멘트.

### ISSUE THREAD

**Issue by zeliard** [mooneegee/CloneCraft#2]
* VS2013에서 OpenGL 라이브러리를 포함시키는 방법은, 수동으로 까는게 아니라,  Nuget이라는 패키지 매니저를 이용해서 설치하는게 좋음. 그래야 나중에 다른데서 .sln 파일 열어봐도 의존성 있는 라이브러리를 인터넷에서 자동으로 가져오기 때문임. 다음을 참고: http://in2gpu.com/2014/11/29/setting-opengl-visual-studio-using-nuget/

* GLAUX를 사용했는데, 이거 꼭 써야할 이유가 있나? 거의 20년전에 단종(?)된 라이브러리인데...
http://stackoverflow.com/questions/3933027/how-to-get-the-gl-library-headers 여기에 보면,
" glaux.h is not a header associated with OpenGL. I assume you've read the awful NEHE tutorials and just went along with it. Glaux is a horribly outdated Win32 library (1996) for loading uncompressed bitmaps. Use something better, like libPNG, which also supports alpha channels."
이렇게 나옴.. 참고하고 대안이 있으면 대안을 사용하는게 좋을것 같음. (정 안되면 glaux라이브러리를 github에 폴더 만들어서 올려야 함)

**Comment by mooneegee** [comment]
다음 주 내로 코멘트해주신 내용을 우선적으로 수정하고 개선하겠습니다.

**Comment by mooneegee** [comment]
6391cf61305bb4b654319359f8b6ee4790bec132
코멘트 하신 내용 모두 적용하였습니다.
