### ISSUE TITLE
FINAL!

### ISSUE THREAD

**Issue by zeliard** [mooneegee/CloneCraft#20]
한 학기 수고 많았다. 
마지막 시연까지도 잘 마무리 했으면 좋겠고,
그 후에도 잘 가다듬어서 너만의 훌륭한 포트폴리오가 되기를 기원한다.

**Comment by mooneegee** [comment]
네 한 학기동안 동안 정말 감사했습니다. 좋은 경험이 된 것 같습니다.

**Comment by zeliard** [comment]
일취월장. 하산하거라..(2%만 더 채우고 ㅋㅋ)
