### ISSUE TITLE
리소스 파일 관리

### ISSUE THREAD

**Issue by zeliard** [mooneegee/CloneCraft#3]
일단 필터 정리 좀 했고,
fae806ab27239d1df10d641f25751426c3156f05

업데이트 받아서 Readme.txt 읽어보삼.. 앞으로 뭔가 해야 될 것을 저기에 업데이트할 수 있음..

**Comment by mooneegee** [comment]
08e2898b9688081d40f488b62d69e0e874cabb1e
resource 관리 수정했습니다.

**Comment by mooneegee** [comment]
좀더 자주 커밋하도록 하겠습니다.
습관이...
